name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message:  "Big thanks 🤗 for bringing matters to our attention!"
        pr-message: "A heartfelt 🥰 thank you for your upcoming pull request! Your efforts power our progress."
